version: "3"
services:
  web:
    container_name: backend_demo
    build: .
    restart: always
    ports:
      - "51005:51005"
    links:
      - mongo
      - mysql
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    restart: on-failure    
    ports:
      - "27017:27017"
  mysql:
    image: mysql:5.7.28
    volumes:
      - ./data:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'backend_demo'
    restart: on-failure
    ports: 
      - "3306:3306"

